Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Fetch RSS Feed and Update Repo
+name: Fetch RSS Feed and Update Rep2
 
 on:
   schedule:
@@ -540,6 +540,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install feedparser
+          pip install requests
 
       - name: Install System Dependencies
         run: |
@@ -607,6 +608,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install feedparser
+          pip install requests
 
       - name: Install System Dependencies
         run: |
@@ -673,6 +675,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install feedparser
+          pip install requests
 
       - name: Install System Dependencies
         run: |
@@ -740,6 +743,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install feedparser
+          pip install requests
 
       - name: Install System Dependencies
         run: |
@@ -806,6 +810,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install feedparser
+          pip install requests
 
       - name: Install System Dependencies
         run: |
@@ -872,6 +877,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install feedparser
+          pip install requests
 
       - name: Install System Dependencies
         run: |
@@ -939,6 +945,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install feedparser
+          pip install requests
 
       - name: Install System Dependencies
         run: |
@@ -1006,6 +1013,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install feedparser
+          pip install requests
 
       - name: Install System Dependencies
         run: |
@@ -1073,6 +1081,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install feedparser
+          pip install requests
 
       - name: Install System Dependencies
         run: |
@@ -1140,6 +1149,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install feedparser
+          pip install requests
 
       - name: Install System Dependencies
         run: |
@@ -1207,6 +1217,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install feedparser
+          pip install requests
 
       - name: Install System Dependencies
         run: |
@@ -1274,6 +1285,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install feedparser
+          pip install requests
 
       - name: Install System Dependencies
         run: |
@@ -1311,6 +1323,342 @@ jobs:
         run: |
           set +e  # Allow the script to continue on errors
           python fetch_rss20.py
+          if [ $? -ne 0 ]; then
+            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
+          fi
+          set -e  # Re-enable stopping on errors
+      - name: Commit and push updated RSS data and GUIDs
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add rss_data.json guids.json
+          git commit -m "Update RSS feed data and GUIDs"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+
+  update-rss21:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install feedparser
+          pip install requests
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update
+          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
+  
+      - name: Install Ollama
+        run: |
+          echo "Installing Ollama CLI..."
+          curl -fsSL https://ollama.com/install.sh | sh
+          ollama --version
+  
+      - name: Start Ollama Service
+        run: |
+          echo "Starting Ollama service..."
+          ollama serve &
+          sleep 5  # Allow time for the service to initialize
+  
+      - name: Verify Ollama Service
+        run: |
+          echo "Checking if Ollama API is running..."
+          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
+  
+      - name: Pull LLaMA Model
+        run: |
+          echo "Pulling the LLaMA 2 model..."
+          if ! ollama pull llama3; then
+            echo "Model pull failed. Please check model availability or permissions."
+            exit 1
+          fi
+
+      - name: Fetch RSS feed and store data
+        run: |
+          set +e  # Allow the script to continue on errors
+          python fetch_rss21.py
+          if [ $? -ne 0 ]; then
+            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
+          fi
+          set -e  # Re-enable stopping on errors
+      - name: Commit and push updated RSS data and GUIDs
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add rss_data.json guids.json
+          git commit -m "Update RSS feed data and GUIDs"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+  update-rss22:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install feedparser
+          pip install requests
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update
+          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
+  
+      - name: Install Ollama
+        run: |
+          echo "Installing Ollama CLI..."
+          curl -fsSL https://ollama.com/install.sh | sh
+          ollama --version
+  
+      - name: Start Ollama Service
+        run: |
+          echo "Starting Ollama service..."
+          ollama serve &
+          sleep 5  # Allow time for the service to initialize
+  
+      - name: Verify Ollama Service
+        run: |
+          echo "Checking if Ollama API is running..."
+          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
+  
+      - name: Pull LLaMA Model
+        run: |
+          echo "Pulling the LLaMA 2 model..."
+          if ! ollama pull llama3; then
+            echo "Model pull failed. Please check model availability or permissions."
+            exit 1
+          fi
+
+      - name: Fetch RSS feed and store data
+        run: |
+          set +e  # Allow the script to continue on errors
+          python fetch_rss22.py
+          if [ $? -ne 0 ]; then
+            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
+          fi
+          set -e  # Re-enable stopping on errors
+      - name: Commit and push updated RSS data and GUIDs
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add rss_data.json guids.json
+          git commit -m "Update RSS feed data and GUIDs"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+  update-rss23:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install feedparser
+          pip install requests
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update
+          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
+  
+      - name: Install Ollama
+        run: |
+          echo "Installing Ollama CLI..."
+          curl -fsSL https://ollama.com/install.sh | sh
+          ollama --version
+  
+      - name: Start Ollama Service
+        run: |
+          echo "Starting Ollama service..."
+          ollama serve &
+          sleep 5  # Allow time for the service to initialize
+  
+      - name: Verify Ollama Service
+        run: |
+          echo "Checking if Ollama API is running..."
+          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
+  
+      - name: Pull LLaMA Model
+        run: |
+          echo "Pulling the LLaMA 2 model..."
+          if ! ollama pull llama3; then
+            echo "Model pull failed. Please check model availability or permissions."
+            exit 1
+          fi
+
+      - name: Fetch RSS feed and store data
+        run: |
+          set +e  # Allow the script to continue on errors
+          python fetch_rss23.py
+          if [ $? -ne 0 ]; then
+            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
+          fi
+          set -e  # Re-enable stopping on errors
+      - name: Commit and push updated RSS data and GUIDs
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add rss_data.json guids.json
+          git commit -m "Update RSS feed data and GUIDs"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+  update-rss24:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install feedparser
+          pip install requests
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update
+          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
+  
+      - name: Install Ollama
+        run: |
+          echo "Installing Ollama CLI..."
+          curl -fsSL https://ollama.com/install.sh | sh
+          ollama --version
+  
+      - name: Start Ollama Service
+        run: |
+          echo "Starting Ollama service..."
+          ollama serve &
+          sleep 5  # Allow time for the service to initialize
+  
+      - name: Verify Ollama Service
+        run: |
+          echo "Checking if Ollama API is running..."
+          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
+  
+      - name: Pull LLaMA Model
+        run: |
+          echo "Pulling the LLaMA 2 model..."
+          if ! ollama pull llama3; then
+            echo "Model pull failed. Please check model availability or permissions."
+            exit 1
+          fi
+
+      - name: Fetch RSS feed and store data
+        run: |
+          set +e  # Allow the script to continue on errors
+          python fetch_rss24.py
+          if [ $? -ne 0 ]; then
+            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
+          fi
+          set -e  # Re-enable stopping on errors
+      - name: Commit and push updated RSS data and GUIDs
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add rss_data.json guids.json
+          git commit -m "Update RSS feed data and GUIDs"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+  update-rss25:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install feedparser
+          pip install requests
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update
+          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
+  
+      - name: Install Ollama
+        run: |
+          echo "Installing Ollama CLI..."
+          curl -fsSL https://ollama.com/install.sh | sh
+          ollama --version
+  
+      - name: Start Ollama Service
+        run: |
+          echo "Starting Ollama service..."
+          ollama serve &
+          sleep 5  # Allow time for the service to initialize
+  
+      - name: Verify Ollama Service
+        run: |
+          echo "Checking if Ollama API is running..."
+          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
+  
+      - name: Pull LLaMA Model
+        run: |
+          echo "Pulling the LLaMA 2 model..."
+          if ! ollama pull llama3; then
+            echo "Model pull failed. Please check model availability or permissions."
+            exit 1
+          fi
+
+      - name: Fetch RSS feed and store data
+        run: |
+          set +e  # Allow the script to continue on errors
+          python fetch_rss25.py
           if [ $? -ne 0 ]; then
             echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
           fi
