Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -790,3 +790,537 @@ jobs:
           git push
         env:
           GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+  update-rss12:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install feedparser
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update
+          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
+  
+      - name: Install Ollama
+        run: |
+          echo "Installing Ollama CLI..."
+          curl -fsSL https://ollama.com/install.sh | sh
+          ollama --version
+  
+      - name: Start Ollama Service
+        run: |
+          echo "Starting Ollama service..."
+          ollama serve &
+          sleep 5  # Allow time for the service to initialize
+  
+      - name: Verify Ollama Service
+        run: |
+          echo "Checking if Ollama API is running..."
+          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
+  
+      - name: Pull LLaMA Model
+        run: |
+          echo "Pulling the LLaMA 2 model..."
+          if ! ollama pull llama3; then
+            echo "Model pull failed. Please check model availability or permissions."
+            exit 1
+          fi
+
+      - name: Fetch RSS feed and store data
+        run: |
+          set +e  # Allow the script to continue on errors
+          python fetch_rss13.py
+          if [ $? -ne 0 ]; then
+            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
+          fi
+          set -e  # Re-enable stopping on errors
+      - name: Commit and push updated RSS data and GUIDs
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add rss_data.json guids.json
+          git commit -m "Update RSS feed data and GUIDs"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+  update-rss14:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install feedparser
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update
+          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
+  
+      - name: Install Ollama
+        run: |
+          echo "Installing Ollama CLI..."
+          curl -fsSL https://ollama.com/install.sh | sh
+          ollama --version
+  
+      - name: Start Ollama Service
+        run: |
+          echo "Starting Ollama service..."
+          ollama serve &
+          sleep 5  # Allow time for the service to initialize
+  
+      - name: Verify Ollama Service
+        run: |
+          echo "Checking if Ollama API is running..."
+          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
+  
+      - name: Pull LLaMA Model
+        run: |
+          echo "Pulling the LLaMA 2 model..."
+          if ! ollama pull llama3; then
+            echo "Model pull failed. Please check model availability or permissions."
+            exit 1
+          fi
+
+      - name: Fetch RSS feed and store data
+        run: |
+          set +e  # Allow the script to continue on errors
+          python fetch_rss14.py
+          if [ $? -ne 0 ]; then
+            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
+          fi
+          set -e  # Re-enable stopping on errors
+      - name: Commit and push updated RSS data and GUIDs
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add rss_data.json guids.json
+          git commit -m "Update RSS feed data and GUIDs"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+
+  update-rss15:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install feedparser
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update
+          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
+  
+      - name: Install Ollama
+        run: |
+          echo "Installing Ollama CLI..."
+          curl -fsSL https://ollama.com/install.sh | sh
+          ollama --version
+  
+      - name: Start Ollama Service
+        run: |
+          echo "Starting Ollama service..."
+          ollama serve &
+          sleep 5  # Allow time for the service to initialize
+  
+      - name: Verify Ollama Service
+        run: |
+          echo "Checking if Ollama API is running..."
+          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
+  
+      - name: Pull LLaMA Model
+        run: |
+          echo "Pulling the LLaMA 2 model..."
+          if ! ollama pull llama3; then
+            echo "Model pull failed. Please check model availability or permissions."
+            exit 1
+          fi
+
+      - name: Fetch RSS feed and store data
+        run: |
+          set +e  # Allow the script to continue on errors
+          python fetch_rss15.py
+          if [ $? -ne 0 ]; then
+            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
+          fi
+          set -e  # Re-enable stopping on errors
+      - name: Commit and push updated RSS data and GUIDs
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add rss_data.json guids.json
+          git commit -m "Update RSS feed data and GUIDs"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+
+  update-rss16:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install feedparser
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update
+          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
+  
+      - name: Install Ollama
+        run: |
+          echo "Installing Ollama CLI..."
+          curl -fsSL https://ollama.com/install.sh | sh
+          ollama --version
+  
+      - name: Start Ollama Service
+        run: |
+          echo "Starting Ollama service..."
+          ollama serve &
+          sleep 5  # Allow time for the service to initialize
+  
+      - name: Verify Ollama Service
+        run: |
+          echo "Checking if Ollama API is running..."
+          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
+  
+      - name: Pull LLaMA Model
+        run: |
+          echo "Pulling the LLaMA 2 model..."
+          if ! ollama pull llama3; then
+            echo "Model pull failed. Please check model availability or permissions."
+            exit 1
+          fi
+
+      - name: Fetch RSS feed and store data
+        run: |
+          set +e  # Allow the script to continue on errors
+          python fetch_rss16.py
+          if [ $? -ne 0 ]; then
+            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
+          fi
+          set -e  # Re-enable stopping on errors
+      - name: Commit and push updated RSS data and GUIDs
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add rss_data.json guids.json
+          git commit -m "Update RSS feed data and GUIDs"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+
+  update-rss17:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install feedparser
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update
+          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
+  
+      - name: Install Ollama
+        run: |
+          echo "Installing Ollama CLI..."
+          curl -fsSL https://ollama.com/install.sh | sh
+          ollama --version
+  
+      - name: Start Ollama Service
+        run: |
+          echo "Starting Ollama service..."
+          ollama serve &
+          sleep 5  # Allow time for the service to initialize
+  
+      - name: Verify Ollama Service
+        run: |
+          echo "Checking if Ollama API is running..."
+          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
+  
+      - name: Pull LLaMA Model
+        run: |
+          echo "Pulling the LLaMA 2 model..."
+          if ! ollama pull llama3; then
+            echo "Model pull failed. Please check model availability or permissions."
+            exit 1
+          fi
+
+      - name: Fetch RSS feed and store data
+        run: |
+          set +e  # Allow the script to continue on errors
+          python fetch_rss17.py
+          if [ $? -ne 0 ]; then
+            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
+          fi
+          set -e  # Re-enable stopping on errors
+      - name: Commit and push updated RSS data and GUIDs
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add rss_data.json guids.json
+          git commit -m "Update RSS feed data and GUIDs"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+
+  update-rss18:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install feedparser
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update
+          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
+  
+      - name: Install Ollama
+        run: |
+          echo "Installing Ollama CLI..."
+          curl -fsSL https://ollama.com/install.sh | sh
+          ollama --version
+  
+      - name: Start Ollama Service
+        run: |
+          echo "Starting Ollama service..."
+          ollama serve &
+          sleep 5  # Allow time for the service to initialize
+  
+      - name: Verify Ollama Service
+        run: |
+          echo "Checking if Ollama API is running..."
+          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
+  
+      - name: Pull LLaMA Model
+        run: |
+          echo "Pulling the LLaMA 2 model..."
+          if ! ollama pull llama3; then
+            echo "Model pull failed. Please check model availability or permissions."
+            exit 1
+          fi
+
+      - name: Fetch RSS feed and store data
+        run: |
+          set +e  # Allow the script to continue on errors
+          python fetch_rss18.py
+          if [ $? -ne 0 ]; then
+            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
+          fi
+          set -e  # Re-enable stopping on errors
+      - name: Commit and push updated RSS data and GUIDs
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add rss_data.json guids.json
+          git commit -m "Update RSS feed data and GUIDs"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+
+  update-rss19:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install feedparser
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update
+          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
+  
+      - name: Install Ollama
+        run: |
+          echo "Installing Ollama CLI..."
+          curl -fsSL https://ollama.com/install.sh | sh
+          ollama --version
+  
+      - name: Start Ollama Service
+        run: |
+          echo "Starting Ollama service..."
+          ollama serve &
+          sleep 5  # Allow time for the service to initialize
+  
+      - name: Verify Ollama Service
+        run: |
+          echo "Checking if Ollama API is running..."
+          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
+  
+      - name: Pull LLaMA Model
+        run: |
+          echo "Pulling the LLaMA 2 model..."
+          if ! ollama pull llama3; then
+            echo "Model pull failed. Please check model availability or permissions."
+            exit 1
+          fi
+
+      - name: Fetch RSS feed and store data
+        run: |
+          set +e  # Allow the script to continue on errors
+          python fetch_rss19.py
+          if [ $? -ne 0 ]; then
+            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
+          fi
+          set -e  # Re-enable stopping on errors
+      - name: Commit and push updated RSS data and GUIDs
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add rss_data.json guids.json
+          git commit -m "Update RSS feed data and GUIDs"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+
+  update-rss20:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install feedparser
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get clean
+          sudo rm -rf /var/lib/apt/lists/*
+          sudo apt-get update
+          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
+  
+      - name: Install Ollama
+        run: |
+          echo "Installing Ollama CLI..."
+          curl -fsSL https://ollama.com/install.sh | sh
+          ollama --version
+  
+      - name: Start Ollama Service
+        run: |
+          echo "Starting Ollama service..."
+          ollama serve &
+          sleep 5  # Allow time for the service to initialize
+  
+      - name: Verify Ollama Service
+        run: |
+          echo "Checking if Ollama API is running..."
+          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
+  
+      - name: Pull LLaMA Model
+        run: |
+          echo "Pulling the LLaMA 2 model..."
+          if ! ollama pull llama3; then
+            echo "Model pull failed. Please check model availability or permissions."
+            exit 1
+          fi
+
+      - name: Fetch RSS feed and store data
+        run: |
+          set +e  # Allow the script to continue on errors
+          python fetch_rss20.py
+          if [ $? -ne 0 ]; then
+            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
+          fi
+          set -e  # Re-enable stopping on errors
+      - name: Commit and push updated RSS data and GUIDs
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+          git add rss_data.json guids.json
+          git commit -m "Update RSS feed data and GUIDs"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
